# Generated by Django 2.1.5 on 2019-01-13 13:02

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_photo',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.image_directory_path),
        ),
    ]
