# Generated by Django 2.1.5 on 2019-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_title_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='concert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
